[PHP]
engine = On
short_open_tag = Off
precision = 14
output_buffering = 4096
serialize_precision = -1
disable_functions =
disable_classes =
max_execution_time = 120
max_input_time = 60
memory_limit = 512M
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = Off
display_startup_errors = Off
log_errors = On
post_max_size = 12M
file_uploads = On
upload_max_filesize = 10M
max_file_uploads = 20
allow_url_fopen = On
allow_url_include = Off
default_socket_timeout = 60
zlib.output_compression=Off

realpath_cache_size=4096K
realpath_cache_ttl=600

; Extensions
extension_dir = "ext"
extension=curl
extension=mbstring
extension=openssl
extension=pdo_sqlite
extension=sqlite3
extension=fileinfo
extension=zip
extension=sodium
extension=bcmath
extension=ctype
extension=tokenizer
extension=dom
extension=xml
extension=pdo
extension=intl
extension=gd
extension=exif 

error_log = "../www/storage/logs/php_errors.log"
upload_tmp_dir = "../www/storage/tmp"

; Date
[Date]
date.timezone = "Asia/Manila"

; Session
[Session]
session.save_handler = files
session.use_strict_mode = 1
session.use_cookies = 1
session.use_only_cookies = 1
session.name = PHPSESSID
session.gc_probability=1
session.gc_divisor=1000
session.gc_maxlifetime=7200
session.sid_length = 26
session.sid_bits_per_character = 5
session.save_path = "../www/storage/sessions"

[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=32
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0
opcache.revalidate_freq=0
opcache.save_comments=1
opcache.jit=1255
opcache.jit_buffer_size=64M